Repository conda-incubator/conda-store-ui, pull requests merged in 2022-08, with the labels that each got.

#48 Dockerization
  Dockerfile
  README.md
  docker-compose.yml
  docker/assets/conda_store_config.py
  docker/assets/environments/python-flask-env.yaml
Labels: enhancement

#47 environment details
  .env.example
  README.md
  package.json
  src/App.tsx
  src/common/interfaces/ApiResponse.ts
  src/common/interfaces/index.ts
  src/common/models/Build.ts
  src/common/models/BuildArtifact.ts
  src/common/models/BuildPackage.ts
  src/common/models/index.ts
  src/components/BlockContainer.tsx
  src/components/index.tsx
  src/features/api/apiSlice.ts
  src/features/artifacts/components/ArtifactsList.tsx
  src/features/artifacts/stories/ArtifactsList.stories.tsx
  src/features/channels/channelsSlice.ts
  src/features/dependencies/components/Dependencies.tsx
  src/features/dependencies/components/DependenciesItem.tsx
  src/features/dependencies/dependenciesApiSlice.ts
  src/features/dependencies/dependenciesSlice.ts
  src/features/dependencies/index.tsx
  src/features/dependencies/stories/Dependencies.stories.tsx
  src/features/environmentDetails/components/EnvironmentDetails.tsx
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
  src/features/environmentDetails/components/Specification/Specification.tsx
  src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
  src/features/environmentDetails/components/Specification/SpecificationReadOnly.tsx
  src/features/environmentDetails/components/Specification/index.tsx
  src/features/environmentDetails/components/index.tsx
  src/features/environmentDetails/environmentDetailsApiSlice.ts
  src/features/environmentDetails/environmentDetailsSlice.ts
  src/features/environmentDetails/index.tsx
  src/features/requestedPackages/requestedPackagesSlice.ts
  src/store/rootReducer.ts
  src/store/selectors/condaSpecificationSelector.ts
  src/utils/helpers/requestedPackageParser.ts
  test/ArtifactsList.test.tsx
  test/BlockContainer.test.tsx
  test/Dependencies.test.tsx
  webpack.config.js
  yarn.lock
Labels: enhancement, high_priority

#50 environment metadata read-only
  package.json
  src/App.tsx
  src/features/artifacts/components/ArtifactList.tsx
  src/features/artifacts/components/index.tsx
  src/features/artifacts/stories/ArtifactsList.stories.tsx
  src/features/environmentDetails/components/EnvironmentDetails.tsx
  src/features/metadata/components/BuildDropdown.tsx
  src/features/metadata/components/EnvMetadata.tsx
  src/features/metadata/components/index.tsx
  src/features/metadata/index.tsx
  src/styles/StyledBox.tsx
  src/styles/StyledMetadataItem.tsx
  src/styles/index.tsx
  src/utils/helpers/buildMapper.ts
  src/utils/helpers/index.ts
  test/ArtifactsList.test.tsx
  test/BuildDropdown.test.tsx
  test/EnvMetadata.test.tsx
  yarn.lock
Labels: enhancement

#51 page layout
  src/App.tsx
  src/features/artifacts/components/ArtifactList.tsx
  src/features/dependencies/components/Dependencies.tsx
  src/features/dependencies/dependenciesApiSlice.ts
  src/features/dependencies/dependenciesSlice.ts
  src/features/environmentDetails/components/EnvironmentDetails.tsx
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
  src/features/environmentDetails/environmentDetailsApiSlice.ts
  src/features/environments/components/Environment.tsx
  src/features/environments/components/EnvironmentDropdown.tsx
  src/features/environments/components/Environments.tsx
  src/features/environments/components/EnvironmentsList.tsx
  src/features/environments/components/EnvironmentsSearch.tsx
  src/features/environments/mocks/mockEnvironments.ts
  src/features/tabs/components/PageTabs.tsx
  src/features/tabs/components/index.tsx
  src/features/tabs/index.tsx
  src/features/tabs/tabsSlice.ts
  src/layouts/PageLayout.tsx
  src/layouts/index.tsx
  src/store/rootReducer.ts
  src/styles/StyledBox.tsx
  src/styles/StyledTab.tsx
  src/styles/StyledTabs.tsx
  src/styles/index.tsx
  test/ArtifactsList.test.tsx
  test/Dependencies.test.tsx
  test/Environment.test.tsx
  test/EnvironmentSearch.test.tsx
  test/testutils.tsx
Labels: enhancement

#59 Login
  .env.example
  docker-compose.yml
  package.json
  src/App.tsx
  src/features/artifacts/components/ArtifactList.tsx
  src/features/environmentDetails/components/EnvironmentDetails.tsx
  src/features/environments/components/EnvironmentsSearch.tsx
  src/features/login/authApiSlice.ts
  src/features/login/authSlice.ts
  src/features/login/components/LoginAlert.tsx
  src/features/login/components/LoginForm.tsx
  src/features/login/components/LoginPage.tsx
  src/features/login/components/index.tsx
  src/features/login/index.ts
  src/features/tabs/components/PageTabs.tsx
  src/store/rootReducer.ts
  test/BuildDropdown.test.tsx
  test/LoginPage.test.tsx
  yarn.lock
Labels: enhancement

#60 namespaces and environments api
  src/features/environments/components/Environments.tsx
  src/features/environments/components/EnvironmentsList.tsx
  src/features/environments/environmentsApiSlice.ts
  src/features/environments/index.ts
  src/features/environments/reducer.ts
  src/features/environments/stories/Environments.stories.tsx
  src/features/tabs/components/PageTabs.tsx
  src/layouts/PageLayout.tsx
Labels: enhancement

#66 change ui title
  webpack.config.js
Labels: chore

#69 fix dropdowns click
  src/components/VersionSelect.tsx
  src/features/metadata/components/BuildDropdown.tsx
Labels: UI

#67 Fix auth/login unit tests
  src/features/login/components/LoginPage.tsx
  test/LoginPage.test.tsx
Labels: bug
