Repository conda-incubator/conda-store-ui, pull requests merged in 2023-09, with the labels that each got.

#280 Typo fixes in `PULL_REQUEST_TEMPLATE.md`
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs: review 👀, type: maintenance 🛠

#281 Improve default yaml environment template
  src/features/artifacts/components/ArtifactList.tsx
  src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
Labels: type: enhancement 💅🏼, status: merge ready 🚀, area: user experience 👩🏻‍💻, project: JATIC

#286 Update LICENSE attribution
  LICENSE
Labels: type: maintenance 🛠, area: community 🌱

#285 Mock `store` with Provider for broken stories
  src/features/dependencies/stories/Dependencies.stories.tsx
  src/features/environments/stories/Environments.stories.tsx
  src/features/requestedPackages/stories/RequestedPackagesEdit.stories.tsx
Labels: type: bug 🐛, area: documentation 📖, area: user experience 👩🏻‍💻

#287 FEAT - Display build time for environments
  src/utils/helpers/buildMapper.ts
Labels: type: enhancement 💅🏼, area: user workflows 🗺

#298 :bookmark: Bump release
  .github/workflows/release.yml
  package.json
Labels: release 🏷

#292 Add new colors and define green theme
  src/App.tsx
  src/colors.tsx
  src/index.tsx
  src/theme.tsx
Labels: type: enhancement 💅🏼, area: UI design 🎨, status: merge ready 🚀
