Repository conda-incubator/conda-store-ui, pull requests merged in 2023-11, with the labels that each got.

#321 Fix environment search tests
  test/environments/EnvironmentSearch.test.tsx
Labels: type: bug 🐛, area: testing ✅

#332 Expose `status_info` in the UI
  src/common/models/Build.ts
  src/features/environmentCreate/components/EnvironmentCreate.tsx
  src/features/metadata/components/EnvBuilds.tsx
  src/utils/helpers/buildMapper.ts
Labels: status: blocked ⛔️

#339 MAINT - Bump nodejs version
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  README.md
  environment_dev.yml
  package.json
Labels: status: merge ready 🚀, type: maintenance 🛠, area: dependencies 📦

#310 ENH - Design system implementation
  package.json
  src/App.tsx
  src/colors.tsx
  src/components/BlockContainerEditMode.tsx
  src/components/ConstraintSelect.tsx
  src/components/Dialog.tsx
  src/components/VersionSelect.tsx
  src/components/icons/ArrowIcon.tsx
  src/components/icons/BookIcon.tsx
  src/components/icons/ChannelIcon.tsx
  src/components/icons/CodeIcon.tsx
  src/components/icons/CondaLogo.tsx
  src/components/icons/DeleteIconAlt.tsx
  src/components/icons/GroupIconAlt.tsx
  src/components/icons/SearchIconAlt.tsx
  src/components/icons/SquareIconAlt.tsx
  src/components/icons/UploadIcon.tsx
  src/components/icons/index.tsx
  src/features/artifacts/components/ArtifactsItem.tsx
  src/features/channels/components/ChannelsEdit.tsx
  src/features/channels/components/ChannelsEditItem.tsx
  src/features/environmentCreate/components/CreateEnvironmentPackages.tsx
  src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
  src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
  src/features/environments/components/Environment.tsx
  src/features/environments/components/EnvironmentDropdown.tsx
  src/features/environments/components/Environments.tsx
  src/features/environments/components/EnvironmentsList.tsx
  src/features/environments/components/EnvironmentsSearch.tsx
  src/features/environments/styles/environmentAddIconStyles.ts
  src/features/environments/styles/index.ts
  src/features/metadata/components/BuildDropdown.tsx
  src/features/metadata/components/Description.tsx
  src/features/metadata/components/EnvMetadata.tsx
  src/features/requestedPackages/components/AddRequestedPackage.tsx
  src/features/requestedPackages/components/RequestedPackagesEdit.tsx
  src/index.tsx
  src/styles/StyledAccordionDetails.tsx
  src/styles/StyledAccordionSummary.tsx
  src/styles/StyledButtonPrimary.tsx
  src/styles/StyledIconButton.tsx
  src/styles/StyledList.tsx
  src/styles/StyledListItem.tsx
  src/styles/StyledScrollContainer.tsx
  src/styles/StyledSwitchButton.tsx
  src/styles/index.tsx
  src/theme.tsx
  webpack.config.js
Labels: type: enhancement 💅🏼, area: UI design 🎨, needs: review 👀
