Repository conda-incubator/conda-store-ui, pull requests merged in 2023-10, with the labels that each got.

#293 ENH - Add Playwright for automated testing
  .env.tpl
  .github/workflows/test.yml
  .gitignore
  environment_dev.yml
  test/playwright/conftest.py
  test/playwright/test_ux.py
Labels: type: enhancement 💅🏼, area: testing ✅, status: in progress 🏗, impact: high 🟥

#319 MAINT - Update release workflow - configure node
  .github/workflows/release.yml
  RELEASE.md
Labels: needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️

#320 Implement design system links
  src/features/artifacts/components/ArtifactsItem.tsx
  src/theme.tsx
Labels: area: UI design 🎨, needs: review 👀, project: JATIC

#304 Implement design system buttons
  src/components/BlockContainerEditMode.tsx
  src/components/Dialog.tsx
  src/components/icons/ArrowIcon.tsx
  src/components/icons/ChannelIcon.tsx
  src/components/icons/CodeIcon.tsx
  src/components/icons/DeleteIconAlt.tsx
  src/components/icons/GroupIconAlt.tsx
  src/components/icons/SearchIconAlt.tsx
  src/components/icons/SquareIconAlt.tsx
  src/components/icons/UploadIcon.tsx
  src/components/icons/index.tsx
  src/features/channels/components/ChannelsEdit.tsx
  src/features/environmentCreate/components/CreateEnvironmentPackages.tsx
  src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
  src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
  src/features/environments/components/Environment.tsx
  src/features/environments/components/EnvironmentDropdown.tsx
  src/features/environments/styles/environmentAddIconStyles.ts
  src/features/environments/styles/index.ts
  src/features/metadata/components/EnvMetadata.tsx
  src/features/requestedPackages/components/RequestedPackagesEdit.tsx
  src/styles/StyledAccordionDetails.tsx
  src/styles/StyledAccordionSummary.tsx
  src/styles/StyledButtonPrimary.tsx
  src/styles/StyledIconButton.tsx
  src/styles/StyledList.tsx
  src/styles/StyledSwitchButton.tsx
  src/styles/index.tsx
  src/theme.tsx
Labels: area: UI design 🎨, needs: changes 🧱, status: in progress 🏗, project: JATIC

#313 Implement design system inputs
  src/components/ConstraintSelect.tsx
  src/components/VersionSelect.tsx
  src/features/channels/components/ChannelsEditItem.tsx
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
  src/features/environments/components/EnvironmentsSearch.tsx
  src/features/metadata/components/BuildDropdown.tsx
  src/features/metadata/components/Description.tsx
  src/features/requestedPackages/components/AddRequestedPackage.tsx
  src/theme.tsx
Labels: area: UI design 🎨, needs: review 👀, project: JATIC
