Repository conda-incubator/conda-store-ui, pull requests merged in 2023-08, with the labels that each got.

#239 Runtime configuration
  src/docs/markdown/CONFIGURATION.md
  src/preferences.tsx
Labels: type: enhancement 💅🏼

#259 Update repository URLs
  README.md
  src/docs/markdown/INSTALL.md
  src/docs/markdown/START.md
Labels: area: user experience 👩🏻‍💻, project: JATIC, area: community 🌱

#263 Fix size of requested packages widget
  src/features/requestedPackages/components/RequestedPackageList.tsx
Labels: type: bug 🐛, area: UI/UX design ✨, impact: high 🟥, project: JATIC

#260 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general_issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: merge ready 🚀, area: user experience 👩🏻‍💻, project: JATIC, area: community 🌱

#270 Remove square icon in dependencies and channel widgets
  src/features/channels/components/Channel.tsx
  src/features/dependencies/components/DependenciesItem.tsx
Labels: type: bug 🐛, area: UI/UX design ✨

#273 Change artifact link names
  src/features/artifacts/components/ArtifactList.tsx
  src/features/artifacts/stories/ArtifactsList.stories.tsx
  src/utils/helpers/artifact.ts
  test/artifacts/ArtifactItem.test.tsx
  test/artifacts/ArtifactsList.test.tsx
  test/helpers/artifact.test.tsx
Labels: type: bug 🐛, needs: review 👀, area: user experience 👩🏻‍💻

#271 ENH - Improve default build selection workflow
  src/features/environmentDetails/components/EnvironmentDetails.tsx
  src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
  src/features/metadata/components/EnvBuilds.tsx
  src/features/metadata/components/EnvMetadata.tsx
  src/features/requestedPackages/components/RequestedPackagesEdit.tsx
  src/features/requestedPackages/components/RequestedPackagesTableRow.tsx
Labels: type: enhancement 💅🏼, needs: changes 🧱, area: user experience 👩🏻‍💻

#276 Add logout functionality and improve login/logout design
  .env.example
  src/components/icons/LoginIcon.tsx
  src/components/icons/index.tsx
  src/docs/markdown/CONFIGURATION.md
  src/features/auth/authApiSlice.ts
  src/features/auth/components/authButton.tsx
  src/features/auth/components/index.tsx
  src/features/auth/index.tsx
  src/features/environments/components/EnvironmentsSearch.tsx
  src/preferences.tsx
Labels: type: enhancement 💅🏼, high priority 🌋, area: UI design 🎨, project: JATIC

#278 Wrap env description in quotes
  src/features/environmentCreate/components/EnvironmentCreate.tsx
Labels: needs: review 👀, area: user experience 👩🏻‍💻
