Repository conda-incubator/conda-store-ui, pull requests merged in 2024-09, with the labels that each got.

#420 MAINT - Update actions
  .github/workflows/build.yml
  .github/workflows/javascript-tests.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: type: maintenance 🛠, area: CI 👷🏽‍♀️, area: dependencies 📦

#421 Fix warning: export 'IPreferences' not found
  src/index.tsx
Labels: type: bug 🐛

#422 Increase Playwright timeouts, robustify YAML editor interaction
  src/features/yamlEditor/components/editor.tsx
  test/playwright/test_ux.py
Labels: type: bug 🐛, area: CI 👷🏽‍♀️

#418 DEV - Improve bundling and release
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/build.yml
  README.md
  RELEASE.md
  docker/assets/conda_store_config.py
  package.json
  tsconfig.eslint.json
  webpack.config.js
  webpack.rules.js
  yarn.lock
Labels: type: bug 🐛, status: in progress 🏗, block-release ⛔️

#424 Remove unnecessary scroll bars from specification tables
  src/features/requestedPackages/components/RequestedPackageList.tsx
  src/styles/StyledAccordionDetails.tsx
Labels: area: components ⚙️

#425 DEV - Refactor release CI workflow
  .github/workflows/build.yml
  .github/workflows/javascript-tests.yml
  .github/workflows/release.yml
  .gitignore
  RELEASE.md
  package.json
Labels: area: CI 👷🏽‍♀️

#427 REL - 2024.9.2-rc1
  package.json
Labels: release 🏷

#415 Fix Docker and upgrade Node
  .github/workflows/javascript-tests.yml
  .github/workflows/pages.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .yarn/releases/yarn-4.4.0.cjs
  .yarnrc.yml
  Dockerfile
  README.md
  docker-compose.yml
  environment_dev.yml
  package.json
Labels: type: enhancement 💅🏼, area: dependencies 📦
