Repository conda-incubator/conda-store-ui, pull requests merged in 2024-03, with the labels that each got.

#370 Fix test warnings
  src/features/environments/components/EnvironmentDropdown.tsx
  src/styles/StyledIconButton.tsx
  test/environmentCreate/CreateEnvironmentPackagesTableRow.test.tsx
  test/environmentDetails/SpecificationEdit.test.tsx
  test/requestedPackages/RequestedPackagesTableRow.test.tsx
Labels: area: testing ✅

#366 Text label for add new environment
  src/features/environments/components/EnvironmentDropdown.tsx
Labels: type: enhancement 💅🏼, area: UI design 🎨

#379 REL - 2024.3.1
  package.json
Labels: release 🏷

#380 BUG - Fix release template links
  .github/ISSUE_TEMPLATE/release.md
Labels: type: bug 🐛

#361 Add namespace to create environment form
  src/features/environmentCreate/components/EnvironmentCreate.tsx
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
  test/environmentDetails/EnvironmentDetailsHeader.test.tsx
  test/playwright/test_ux.py
Labels: area: UI design 🎨, area: user experience 👩🏻‍💻
