Repository conda-incubator/conda-store-ui, pull requests merged in 2024-11, with the labels that each got.

#438 Add "canceled" build status
  src/utils/helpers/buildMapper.ts
  test/helpers/BuildMapper.test.tsx
  test/playwright/conftest.py
  test/playwright/test_ux.py
Labels: type: enhancement 💅🏼, area: UI design 🎨, status: merge ready 🚀

#443 Fix links to build artifacts
  src/features/artifacts/components/ArtifactsItem.tsx
  src/features/metadata/components/EnvBuildStatus.tsx
  src/hooks.ts
  src/utils/helpers/parseArtifactList.ts
  test/artifacts/ArtifactsList.test.tsx
Labels: block-release ⛔️

#445 REL - 2024.11.1
  package.json
Labels: release 🏷

#446 DOC - Add links to version specification
  .github/ISSUE_TEMPLATE/release.md
  README.md
  RELEASE.md
Labels: area: documentation 📖
