Repository conda-incubator/conda-store-ui, pull requests merged in 2024-01, with the labels that each got.

#348 MAINT - Miscellaneous improvements to readme
  README.md
Labels: area: documentation 📖, status: merge ready 🚀, type: maintenance 🛠

#353 DEV - Add scope to release action
  .github/workflows/release.yml
Labels: type: bug 🐛, area: CI 👷🏽‍♀️

#349 Remove narrative UI docs from Storybook
  .storybook/main.js
  .storybook/preview.js
  src/docs/Testing.stories.mdx
  src/docs/Welcome.stories.mdx
  src/docs/configuration.stories.mdx
  src/docs/development.stories.mdx
  src/docs/gettingStarted.stories.mdx
  src/docs/markdown/CONFIGURATION.md
  src/docs/markdown/DEVELOPMENT.md
  src/docs/markdown/INTRODUCTION.md
  src/docs/markdown/START.md
  src/docs/release.stories.mdx
Labels: area: documentation 📖, needs: review 👀, type: maintenance 🛠

#357 Tests pass (but with console errors and warnings)
  src/features/requestedPackages/components/AddRequestedPackage.tsx
  test/components/BlockContainerEditMode.test.tsx
  test/environmentCreate/SpecificationCreate.test.tsx
  test/environmentDetails/SpecificationEdit.test.tsx
  test/environments/EnvironmentList.test.tsx
  test/testutils.tsx
Labels: type: bug 🐛, area: testing ✅, status: merge ready 🚀

#282 Disable ability to edit locked environments
  src/features/environmentDetails/components/EnvironmentDetailsHeader.tsx
Labels: type: enhancement 💅🏼, needs: discussion 💬, area: user experience 👩🏻‍💻
