Repository conda-incubator/conda-store-ui, pull requests merged in 2024-02, with the labels that each got.

#369 Create javascript-tests.yml
  .github/workflows/javascript-tests.yml
Labels: area: testing ✅, status: merge ready 🚀

#372 Fix playwright tests
  test/playwright/test_ux.py
  yarn.lock
Labels: area: testing ✅, needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️

#354 Allow passing `variables` via raw YAML
  src/common/models/CondaSpecification.ts
  src/features/environmentCreate/components/Specification/SpecificationCreate.tsx
  src/features/environmentCreate/environmentCreateSlice.ts
  src/features/environmentDetails/components/Specification/SpecificationEdit.tsx
  src/features/environmentVariables/environmentVariablesSlice.ts
  src/features/environmentVariables/index.tsx
  src/features/yamlEditor/components/editor.tsx
  src/store/rootReducer.ts
  src/store/selectors/condaSpecificationSelector.ts
  test/environmentCreate/SpecificationCreate.test.tsx
Labels: type: bug 🐛, status: merge ready 🚀, area: user experience 👩🏻‍💻, area: dependencies 📦
